version: '3.4'

services:
  db:
    image: mariadb
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
    networks:
      - internal
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: craft

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    networks:
      - internal
    ports:
      - 8081:80
    environment:
      UPLOAD_LIMIT: 100M

  php:
    build:
      context: ./cms
      target: php
    depends_on:
      - db
    networks:
      - internal
    volumes:
      - ./cms/config/license.key:/data/config/license.key
      - ./cms/storage:/data/storage
      - ./cms/web/cpresources:/data/web/cpresources
      - ./cms/.env:/data/.env
    environment:
      UPLOAD_LIMIT: 100M

  web:
    build:
      context: ./cms
      target: nginx
    depends_on:
      - php
    networks:
      - internal
    ports:
      - 8080:80
    environment:
      HOST: localhost
    volumes:
      - ./cms-nginx.conf:/etc/nginx/conf.d/default.conf:ro

      - ./cms/web/cpresources:/data/web/cpresources

networks:
  internal:
    external: false

volumes:
  database:
