version: "3.4"

services:
  db:
    image: mariadb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--password=password"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - internal
    volumes:
      - database-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: craft

  php:
    build:
      context: .
      target: php
    depends_on:
      - db
    networks:
      - internal
    volumes:
      - .:/app:rw,cached
    environment:
      PHP_MAX_EXECUTION_TIME: 0
      ENVIRONMENT: dev
      APP_ID: "CraftCMS--!justfordev!"
      SECURITY_KEY: "!justfordev!"
      DB_DRIVER: mysql
      DB_SERVER: db
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: craft
      DEFAULT_SITE_URL: http://localhost

  web:
    build:
      context: .
      target: nginx
    depends_on:
      - php
    networks:
      - internal
    ports:
      - 80:80
    volumes:
      - ./web:/app/web:ro

networks:
  internal:
    external: false

volumes:
  database-mysql:
