version: '3.4'

services:
  db:
    image: mariadb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--password=password"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - internal
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appDb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    networks:
      - internal
    ports:
      - 81:80
    environment:
      UPLOAD_LIMIT: 100M

  # db:
  #   image: postgres
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "--username=postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - internal
  #   volumes:
  #     - ./docker/pgsql:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: appDb

  # pgadmin:
  #   image: dpage/pgadmin4
  #   networks:
  #     - internal
  #   ports:
  #     - 81:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@localhost
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   volumes:
  #     - type: bind
  #       source: ./docker/pgadmin_servers.json
  #       target: /pgadmin4/servers.json

  redis:
    image: redis
    # command: redis-server --appendonly yes --requirepass password
    command: redis-server --appendonly yes
    networks:
      - internal
    volumes:
      - ./docker/redis:/data

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    environment:
      REDIS_1_HOST: redis
      REDIS_1_NAME: AppRedis
    depends_on:
      - redis
    networks:
      - internal
    ports:
      - 82:80

  php:
    build:
      context: .
      target: php
      cache_from:
        - ${PHP_IMAGE_CACHE:-d3strukt0r/a-design-cms-php}
    image: ${PHP_IMAGE:-d3strukt0r/a-design-cms-php}
    healthcheck:
      start_period: 1m40s
    depends_on:
      - db
      - redis
    networks:
      - internal
    volumes:
      # - ./docker/php/www-local.ini:/etc/php7/php-fpm.d/www.conf:ro,cached
      - .:/app:rw
    environment:
      # PHP Settings
      PHP_MAX_EXECUTION_TIME: 0

      # Craft general settings
      ENVIRONMENT: dev # dev, staging, production
      APP_ID: CraftCMS--4c262fd5-5d79-4207-9117-725a1ed4603a
      SECURITY_KEY: FnKtqveecwgMavLwQnX2I-dqYjpwZMR6

      # Craft database settings
      # DB_DRIVER: pgsql
      # DB_SERVER: db
      # DB_PORT: 5432
      # DB_USER: postgres
      # DB_PASSWORD: password
      # DB_DATABASE: project
      # DB_SCHEMA: public
      # DB_TABLE_PREFIX:

      DB_DRIVER: mysql
      DB_SERVER: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: appDb

      # URL & path settings
      ASSETS_URL: http://localhost/assets
      SITE_URL: http://localhost

      # Craft & Plugin Licenses
      # LICENSE_KEY:

      # Redis settings
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
      REDIS_DEFAULT_DB: 0
      REDIS_CRAFT_DB: 3

      # Google Analytics settings
      # GA_TRACKING_ID:

  nginx:
    build:
      context: .
      target: nginx
      cache_from:
        - ${PHP_IMAGE_CACHE:-d3strukt0r/a-design-cms-php}
        - ${NGINX_IMAGE_CACHE:-d3strukt0r/a-design-cms-nginx}
    image: ${NGINX_IMAGE:-d3strukt0r/a-design-cms-nginx}
    healthcheck:
      test: test -e /var/run/nginx.pid || exit 1
    depends_on:
      - php
    networks:
      - internal
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./web:/app/web:ro,cached
    # environment:
    #   USE_HTTPS: "true"

networks:
  internal:
    external: false
