version: "3.4"

services:
  db:
    image: postgres
    networks:
      - internal
    volumes:
      - database-pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: craft

  php:
    build:
      context: .
      target: php
    depends_on:
      - db
    networks:
      - internal
    volumes:
      - .:/app:rw,cached
    environment:
      PHP_MAX_EXECUTION_TIME: 0
      ENVIRONMENT: dev
      APP_ID: "CraftCMS--!justfordev!"
      SECURITY_KEY: "!justfordev!"
      DB_DRIVER: pgsql
      DB_SERVER: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_DATABASE: craft
      DEFAULT_SITE_URL: http://localhost

  web:
    build:
      context: .
      target: nginx
    depends_on:
      - php
    networks:
      - internal
    ports:
      - 80:80
    volumes:
      - ./web/cpresources:/app/web/cpresources:ro

networks:
  internal:
    external: false

volumes:
  database-pgsql:
