version: "3.4"

services:
  db:
    image: mariadb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - internal
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: craft

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    networks:
      - internal
    ports:
      - 8081:80
    environment:
      UPLOAD_LIMIT: 100M

  php:
    build:
      context: .
      target: php
    depends_on:
      - db
    networks:
      - internal
    volumes:
      - .:/app:rw,cached
    environment:
      ENVIRONMENT: dev
      SECURITY_KEY: vrjqathp839q4hjtvio3qpjt438
      DB_HOST: db
      DB_DSN: mysql:host=db;port=3306;dbname=craft
      DB_USER: root
      DB_PASSWORD: password
      DEFAULT_SITE_URL: http://localhost:8080

  web:
    build:
      context: .
      target: nginx
    depends_on:
      - php
    networks:
      - internal
    ports:
      - 8080:80
    environment:
      NGINX_CLIENT_MAX_BODY_SIZE: 100M
    volumes:
      - ./web/cpresources:/app/web/cpresources:ro

networks:
  internal:
    external: false

volumes:
  database:
