version: "3.4"

services:
  db:
    image: mariadb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - internal
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: craft

  php:
    build:
      context: .
      target: php
    depends_on:
      - db
    networks:
      - internal
    volumes:
      - .:/app:rw,cached
    environment:
      ENVIRONMENT: dev
      APP_ID: "CraftCMS--!justfordev!"
      SECURITY_KEY: "!justfordev!"
      DB_SERVER: db
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: craft
      DEFAULT_SITE_URL: http://localhost

  web:
    build:
      context: .
      target: nginx
    depends_on:
      - php
    networks:
      - internal
    ports:
      - 80:80
    volumes:
      - ./web/cpresources:/app/web/cpresources:ro

networks:
  internal:
    external: false

volumes:
  database:
