version: '3.4'

services:
  db:
    image: mariadb
    volumes:
      #
      # Copy in our configs
      #
      - ./cms/docker/charset.cnf:/etc/mysql/conf.d/charset.cnf
      #
      # Persist our MySQL data
      #
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: craft

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    links:
      - db
    volumes:
      #
      # Copy in our PHP config for large uploads.
      #
      - ./cms/docker/uploads2.ini:/usr/local/etc/php/conf.d/uploads.ini

  php:
    build:
      context: ./cms
      target: php
    links:
      - db
    volumes:
      #
      # Copy in our PHP config for large uploads.
      #
      - ./cms/docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

      - ./cms/config/license.key:/data/config/license.key
      - ./cms/storage:/data/storage
      - ./cms/web/cpresources:/data/web/cpresources
      - ./cms/.env:/data/.env

  web:
    build:
      context: ./cms
      target: nginx
    ports:
      - 8080:80
    links:
      - php
    environment:
      - HOST=localhost
    volumes:
      #
      # Import our Nginx configuration for FPM.
      #
      - ./cms/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro

      - ./cms/web/cpresources:/data/web/cpresources

volumes:
  database:
