version: '3.4'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example

  php:
    build:
      context: ./cms
      target: carftcms_php
    depends_on:
      - db
    volumes:
      - ./storage:/srv/api/storage

  cms:
    build:
      context: ./cms
      target: carftcms_nginx
    depends_on:
      - php
    ports:
      - 80:80
