version: "3.4"

services:
  db:
    image: mariadb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--password=password"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - internal
    volumes:
      - database-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: craft

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    networks:
      - internal
    ports:
      - 81:80
    environment:
      UPLOAD_LIMIT: 100M

  # db2:
  #   image: postgres
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "--username=postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - internal
  #   volumes:
  #     - database-pgsql:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: craft

  redis:
    image: redis
#    command: redis-server --appendonly yes --requirepass password
    command: redis-server --appendonly yes
    networks:
      - internal
    volumes:
      - redis-data:/data

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    environment:
      REDIS_1_HOST: redis
      REDIS_1_NAME: MyRedis
    depends_on:
      - redis
    networks:
      - internal
    ports:
      - 82:80

  php:
    build:
      context: .
      target: php
      cache_from:
        - ${PHP_IMAGE_CACHE:-d3strukt0r/a-design-cms-php}
    image: ${PHP_IMAGE:-d3strukt0r/a-design-cms-php}
    healthcheck:
      start_period: 1m40s
    depends_on:
      - db
      - redis
    networks:
      - internal
    volumes:
      - .:/app:rw,cached
    environment:
      # PHP Settings
      PHP_MAX_EXECUTION_TIME: 0

      # Craft general settings
      APP_ID: CraftCMS--4c262fd5-5d79-4207-9117-725a1ed4603a
      ALLOW_UPDATES: "true"
      ALLOW_ADMIN_CHANGES: "true"
      BACKUP_ON_UPDATE: "false"
      DEV_MODE: "true"
      ENABLE_TEMPLATE_CACHING: "false"
      ENVIRONMENT: dev # dev, staging, production
      IS_SYSTEM_LIVE: "true"
      RUN_QUEUE_AUTOMATICALLY: "true"
      SECURITY_KEY: FnKtqveecwgMavLwQnX2I-dqYjpwZMR6

      # Craft database settings
      # DB_DRIVER: pgsql
      # DB_SERVER: db
      # DB_PORT: 5432
      # DB_USER: project
      # DB_PASSWORD: password
      # DB_DATABASE: project
      # DB_SCHEMA: public
      # DB_TABLE_PREFIX:

      DB_DRIVER: mysql
      DB_SERVER: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: craft
      # DB_TABLE_PREFIX:

      # URL & path settings
      ASSETS_URL: http://localhost/assets
      SITE_URL: http://localhost

      # Craft & Plugin Licenses
      # LICENSE_KEY:

      # Redis settings
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
      REDIS_DEFAULT_DB: 0
      REDIS_CRAFT_DB: 3

      # Google Analytics settings
      # GA_TRACKING_ID:

  nginx:
    build:
      context: .
      target: nginx
      cache_from:
        - ${PHP_IMAGE_CACHE:-d3strukt0r/a-design-cms-php}
        - ${NGINX_IMAGE_CACHE:-d3strukt0r/a-design-cms-nginx}
    image: ${NGINX_IMAGE:-d3strukt0r/a-design-cms-nginx}
    healthcheck:
      test: test -e /var/run/nginx.pid || exit 1
    depends_on:
      - php
    networks:
      - internal
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./web:/app/web:ro
    # environment:
    #   USE_HTTPS: "true"

networks:
  internal:
    external: false

volumes:
  database-mysql:
  # database-pgsql:
  redis-data:
