version: '3.4'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: craft
    volumes:
      - ./docker/charset.cnf:/etc/mysql/conf.d/charset.cnf
      - database2:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - ./docker/uploads2.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 8081:80
    links:
      - db

  php:
    build:
      context: .
      target: php
    links:
      - db
    environment:
      ENVIRONMENT: dev
      SECURITY_KEY: some_random_key
      DB_DSN: mysql:host=db;port=3306;dbname=craft
      DB_USER: root
      DB_PASSWORD: password
      DEFAULT_SITE_URL: http://localhost:8080
    volumes:
      - ./docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./config/license.key:/app/config/license.key
      - ./storage:/app/storage
      - ./web/cpresources:/app/web/cpresources
      - ./.env:/app/.env

  web:
    build:
      context: .
      target: nginx
    links:
      - php
    environment:
      - HOST=localhost
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web/cpresources:/app/web/cpresources
    ports:
      - 8080:80

volumes:
  database2:
