fieldLayouts:
  c0251ccc-f021-4fbe-abab-9722fb345a5b:
    tabs:
      -
        elements:
          -
            fieldUid: 9b55f22d-2aee-4c64-8dc6-9988cdf8faba
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
handle: footer
name: Footer
